name: Build

on:
  push:
    branches: [*]

jobs:
  build:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run:
          npm run test
      - run:
          npm run build:prod
